// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnvhcaaqaasbhrnfgtwy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFudmhjYWFxYWFzYmhybmZndHd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0NzA3MDcsImV4cCI6MjA2MzA0NjcwN30.glMf_SS3qjNix7DKsHdfivUikeKAdE4Pmi6KCgjlqpw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);